### ISSUE TITLE
about "usb_rx_count" error

### ISSUE THREAD

**Issue by Alexi2008** [ElectricThanhTung/USB_STC8F#1]
Hi, Dear friend (^_^)
I had tested your usb code, it's very nice!
when i test the variable "usb_rx_count" and find a bug:
"usb_rx.asm" need insert "**CLR C**" before "**SUBB A, R0**"

END1_RX:
    MOV     A, #13
    SUBB    A, R0
-->
END1_RX:
    MOV     A, #13
    **CLR     C**
    SUBB    A, R0

END2_RX:
    MOV     A, #13
    SUBB    A, R0
-->
END2_RX:
    MOV     A, #13
    **CLR     C**
    SUBB    A, R0

**Comment by ElectricThanhTung** [comment]
Thank you for your interest in the project. You were right to find the
error and I also fixed it as your suggestion


Vào Th 2, 4 thg 11, 2019 vào lúc 14:20 Alexi2008 <notifications@github.com>
đã viết:
